name: Continuous Delivery

on: 
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Simulating Continuous Delivery
      uses: actions/upload-artifact@v4
      with:
        name: projetozipado2.zip
        path: calculadora.py

  deploy:
        runs-on: ubuntu-latest
        needs: deliver
        steps: 
            - uses: actions/download-artifact@v4
              with: 
                name: projetozipado2.zip
            - name: Display structure of downloaded files
              run: ls -R

  buildx:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
        -
            name: Checkout
            uses: actions/checkout@v4
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3



