name: Basic CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Print hello world
      run: echo "✅ CI funcionando! Commit: ${{ github.sha }}"
    
    - name: List files
      run: ls -la